[package]
name = "train_example"
type = "contract"
authors = [""]
compiler_version = "1.0.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.1.2", directory="noir-projects/aztec-nr/aztec" }
# If you use this dependency the contract will compile
# token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.1.2", directory="noir-projects/noir-contracts/contracts/app/token_contract" }
# If you use this dependency it wont compile (it's tagged a v1.1.0, but the underlying code uses v1.1.2)
token_contract = { git="https://github.com/defi-wonderland/aztec-standards/", tag="v1.1.0", directory="src/token_contract" }
